### ISSUE TITLE
Strange Clipping with Some LUTs

### ISSUE THREAD

**Issue by so-rose** [so-rose/openlut#3]
Not sure what's going on. Example from applying one such strange LUT:
![lutted](https://cloud.githubusercontent.com/assets/8473401/18257186/d0259d92-738d-11e6-8564-8981e2ea4b87.jpg)

**Comment by dannephoto** [comment]
Did you include some setting which the 1D lut can,t handle? Usually occurs when applying "out of boundary" settings.

**Comment by so-rose** [comment]
Interesting - Couldn't it then have something to do with the Data/Legal range issue, since they aren't properly handled yet, and explicitly deal with boundary settings like you say?

I'll try to fix that and see if it fixes this.
